//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kirillov_chat_api_api_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatRoomEmployee
    {
        public int id { get; set; }
        public int idChatRoom { get; set; }
        public int idEmployee { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
